version: '3.8'

services:
  # El contenedor de la bd
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    # healthcheck para que la app espere a que la bd esté lista
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # El contenedor
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      # Conexión a la bd dentro de la red
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      
      # URL para que docker pueda salir y conectarse al Ollama
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      
      # Claves
      - GPT_OSS_KEY=${GPT_OSS_KEY}
      - BASE_URL_OSS=${BASE_URL_OSS}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_TRACING=true
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
    
    depends_on:
      db:
        condition: service_healthy